### ISSUE TITLE
Reflect changes in foundry-rpc-js on its e2e tests

### ISSUE THREAD

**Issue by somniumism** [CodeChain-io/foundry-rpc-js#21]
foundry-rpc-js was created from codechian-rpc-js, and has newly added functions and changed types. However, the changes were not reflected on the e2e tests, so it's not working. We need to reflect the changes onto e2e tests in foundry-rpc-js.

**Comment by somniumism** [comment]
I ran the e2e tests as follows:
1. Run the foundry solo: `./target/debug/foundry -c solo`
2. Run a command `yarn install` on the alpha-2 branch of foundry-rpc-js
3. Run a command `yarn run test` on the alpha-2 branch of foundry-rpc-js

The results were as follows:
```
  38 passing (466ms)
  9 failing

  1) account
       importRaw:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-importRaw-account_importRaw-49fc767c"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) account
       sign:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-sign-account_importRaw-a74d4f5f"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) account
       cannot sign without passphrase:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-sign2-account_importRaw-1c914faa"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) account
       unlock:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-unlock-account_importRaw-eb016d12"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  5) account
       unlock with duration:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-unlock2-account_importRaw-6ff14d59"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  6) account
       changePassword:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 64, expected a 0x-prefixed hex string with length of 128."
  }
  "id": "account-changePassword-account_importRaw-8c89b80"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  7) chain
       genesis accounts:

      AssertionError: expected [ Array(10) ] to deeply equal [ Array(10) ]
      + expected - actual

       [
         "tccq8vapdlstar6ghmqgczp6j2e83njsqq0tsvaxm9u"
      -  "tccqxphelyu2n73ekpewrsyj0256wjhn2aqds9xrrrg"
      +  "tccq9h7vnl68frvqapzv3tujrxtxtwqdnxw6yamrrgd"
         "tccqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqc2ul2h"
         "tccqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq5duemmc"
         "tccqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqcuzl32l"
         "tccqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgfrhflv"
      
      at Context.<anonymous> (e2e/chain.test.ts:30:31)
      at step (e2e/chain.test.ts:33:23)
      at Object.next (e2e/chain.test.ts:14:53)
      at fulfilled (e2e/chain.test.ts:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  8) devel
       testTPS:
     Error: the object {
  "error": {
    "code": -32032
    "data": "InsufficientBalance { address: Address(0x009f715d65a58dc96dd7a2ac18d4e83f565baba8), balance: 0, cost: 10 }"
    "message": "Not Enough Balance"
  }
  "id": "devel-getBlockSyncPeers-devel_testTPS-34d99d93"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  9) net
       register remote key:
     Error: the object {
  "error": {
    "code": -32602
    "message": "Invalid params: invalid length 128, expected a 0x-prefixed hex string with length of 64."
  }
  "id": "net-register-remote-key-net_registerRemoteKeyFor-231c3e31"
  "jsonrpc": "2.0"
} was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
